apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: lvms
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  installPlanApproval: Automatic
  name: lvms-operator
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
