---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openstack
  namespace: openstack-operators
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/openstack-operator.openstack-operators: ""
  name: openstack-operator
  namespace: openstack-operators
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable-v1.0
  installPlanApproval: Automatic
  name: openstack-operator
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
